import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styles from "@/app/styles/styles.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.header}>
          <ul>
            <li>
              <Link href="/home/">Trang Chủ</Link>
            </li>
            <li>
              <Link href="/category">Thể Loại</Link>
            </li>
            <li>
              <Link href="/profile">Cá Nhân</Link>
            </li>
            
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
