import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "@/node_modules/next/link";
import styles from "@/app/styles/styles.module.css"
import { ReduxProvider } from "./store/provider";
import Header from "./header/page";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
