import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "@/node_modules/next/link";
import styles from "@/app/styles/styles.module.css"
import { ReduxProvider } from "./store/provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.header}>
          <ul>
            <li>
              <Link href="/home/"><div className={styles.menutop}>
              <img src="/icons/home.png"/>Trang Chủ</div>
              </Link>
            </li>
            <li>
              <div className={styles.menutop}>
              <img src="/icons/category.png"/>
              <Link href="/category">Thể Loại</Link>
              </div>
            </li>
            <li>
            <div className={styles.menutop}>
              <img src="/icons/people.png"/>
              <Link href="/profile">Cá Nhân</Link>
              </div>
            </li>
            
          </ul>
        </div>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
